### ISSUE TITLE
please convert the build system to something that doesn't require autotools

### ISSUE THREAD

**Issue by anoraktrend** [void-linux/musl-fts#13]
in gnu-free systems, the reliance on autotools is fairly concerning, especially when one doesn't need it like this project.

**Comment by Duncaen** [comment]
Making systems gnu-free is not of importance for our purpose.

**Comment by anoraktrend** [comment]
> Making systems "gnu-free" is not of importance for our purpose.

Not the issue. Making systems gnu free is the purpose of other projects. Note, I mentioned “In gnu-free systems” not “In making systems gnu-free”.  I have a gnu-free-distro I’m using. I wanted to use this project. I couldn’t and now won’t, considering the more useful implementation/fork from chimera.
