### ISSUE TITLE
Any updates on this as well?

### ISSUE THREAD

**Issue by firasuke** [void-linux/musl-fts#9]
Hey there,

Are there any chances that you're going to keep this on par with the latest fts implementation from NetBSD?

Thank you for your time and effort.

**Comment by Vaelatern** [comment]
Why do you ask?

Same deal as the other issue thread https://github.com/void-linux/musl-obstack/issues/3. Are you promising work? Raising awareness of an issue? Do you think there are problems if you receive one answer instead of another answer?
